# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QPushButton, QSizePolicy, QStackedWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(777, 511)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.firstScreen = QStackedWidget(self.centralwidget)
        self.firstScreen.setObjectName(u"firstScreen")
        self.firstScreen.setGeometry(QRect(0, 0, 771, 511))
        self.UserPage = QWidget()
        self.UserPage.setObjectName(u"UserPage")
        self.UserPage.setStyleSheet(u"#UserPage{\n"
" background-color: rgb(152, 219, 255)\n"
"}")
        self.frame = QFrame(self.UserPage)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(20, 90, 741, 401))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.signerBtn1 = QPushButton(self.frame)
        self.signerBtn1.setObjectName(u"signerBtn1")
        self.signerBtn1.setGeometry(QRect(10, 10, 221, 381))
        icon = QIcon()
        icon.addFile(u"D:/demo2/images/sign1.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.signerBtn1.setIcon(icon)
        self.signerBtn1.setIconSize(QSize(241, 401))
        self.speakerBtn1 = QPushButton(self.frame)
        self.speakerBtn1.setObjectName(u"speakerBtn1")
        self.speakerBtn1.setGeometry(QRect(250, 10, 221, 381))
        icon1 = QIcon()
        icon1.addFile(u"D:/demo2/images/speak.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.speakerBtn1.setIcon(icon1)
        self.speakerBtn1.setIconSize(QSize(251, 441))
        self.learnerBtn1 = QPushButton(self.frame)
        self.learnerBtn1.setObjectName(u"learnerBtn1")
        self.learnerBtn1.setGeometry(QRect(484, 13, 241, 371))
        icon2 = QIcon()
        icon2.addFile(u"D:/demo2/images/learn.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.learnerBtn1.setIcon(icon2)
        self.learnerBtn1.setIconSize(QSize(241, 401))
        self.label1 = QLabel(self.UserPage)
        self.label1.setObjectName(u"label1")
        self.label1.setGeometry(QRect(110, 30, 511, 41))
        font = QFont()
        font.setFamilies([u"Comic Sans MS"])
        font.setPointSize(22)
        font.setBold(True)
        self.label1.setFont(font)
        self.firstScreen.addWidget(self.UserPage)
        self.SecondPage = QWidget()
        self.SecondPage.setObjectName(u"SecondPage")
        self.frame_2 = QFrame(self.SecondPage)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(0, 0, 131, 511))
        self.frame_2.setStyleSheet(u"#frame_2{\n"
" background-color: rgb(239, 176, 255)\n"
"}")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 121, 41))
        font1 = QFont()
        font1.setFamilies([u"Papyrus"])
        font1.setPointSize(24)
        self.label.setFont(font1)
        self.signerBtn2 = QPushButton(self.frame_2)
        self.signerBtn2.setObjectName(u"signerBtn2")
        self.signerBtn2.setGeometry(QRect(10, 60, 75, 24))
        self.speakerBtn2 = QPushButton(self.frame_2)
        self.speakerBtn2.setObjectName(u"speakerBtn2")
        self.speakerBtn2.setGeometry(QRect(10, 100, 75, 24))
        self.learnerBtn2 = QPushButton(self.frame_2)
        self.learnerBtn2.setObjectName(u"learnerBtn2")
        self.learnerBtn2.setGeometry(QRect(10, 140, 75, 24))
        self.feedback2 = QPushButton(self.frame_2)
        self.feedback2.setObjectName(u"feedback2")
        self.feedback2.setGeometry(QRect(10, 180, 75, 24))
        self.secondScreen = QStackedWidget(self.SecondPage)
        self.secondScreen.setObjectName(u"secondScreen")
        self.secondScreen.setGeometry(QRect(130, 0, 651, 511))
        self.secondScreen.setStyleSheet(u"#secondScreen{\n"
"	background-color: rgb(153, 255, 130);\n"
"}")
        self.signerPage = QWidget()
        self.signerPage.setObjectName(u"signerPage")
        self.cameraLabel = QLabel(self.signerPage)
        self.cameraLabel.setObjectName(u"cameraLabel")
        self.cameraLabel.setGeometry(QRect(10, 10, 621, 361))
        self.startBtn1 = QPushButton(self.signerPage)
        self.startBtn1.setObjectName(u"startBtn1")
        self.startBtn1.setGeometry(QRect(280, 380, 75, 24))
        self.frame_3 = QFrame(self.signerPage)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(10, 420, 621, 80))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.soundButton2 = QPushButton(self.frame_3)
        self.soundButton2.setObjectName(u"soundButton2")
        self.soundButton2.setGeometry(QRect(10, 20, 61, 61))
        icon3 = QIcon()
        icon3.addFile(u"../Users/Nimsang/.designer/Users/Nimsang/Downloads/speaker.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.soundButton2.setIcon(icon3)
        self.soundButton2.setIconSize(QSize(65, 61))
        self.outputLabel = QLabel(self.frame_3)
        self.outputLabel.setObjectName(u"outputLabel")
        self.outputLabel.setGeometry(QRect(110, 15, 501, 51))
        self.outputLabel.setWordWrap(True)
        self.secondScreen.addWidget(self.signerPage)
        self.learnerPage = QWidget()
        self.learnerPage.setObjectName(u"learnerPage")
        self.learnerScreen = QStackedWidget(self.learnerPage)
        self.learnerScreen.setObjectName(u"learnerScreen")
        self.learnerScreen.setGeometry(QRect(20, 30, 601, 451))
        self.screen0 = QWidget()
        self.screen0.setObjectName(u"screen0")
        self.Alphabets = QPushButton(self.screen0)
        self.Alphabets.setObjectName(u"Alphabets")
        self.Alphabets.setGeometry(QRect(20, 20, 251, 241))
        self.Test = QPushButton(self.screen0)
        self.Test.setObjectName(u"Test")
        self.Test.setGeometry(QRect(290, 20, 251, 241))
        self.learnerScreen.addWidget(self.screen0)
        self.alphabetScreen = QWidget()
        self.alphabetScreen.setObjectName(u"alphabetScreen")
        self.label_2 = QLabel(self.alphabetScreen)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(190, -11, 271, 51))
        font2 = QFont()
        font2.setFamilies([u"Comic Sans MS"])
        font2.setPointSize(28)
        font2.setBold(True)
        self.label_2.setFont(font2)
        self.frame_4 = QFrame(self.alphabetScreen)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(80, 60, 481, 381))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.alphabet = QLabel(self.frame_4)
        self.alphabet.setObjectName(u"alphabet")
        self.alphabet.setGeometry(QRect(60, 10, 361, 311))
        self.letter = QLabel(self.frame_4)
        self.letter.setObjectName(u"letter")
        self.letter.setGeometry(QRect(250, 335, 31, 21))
        self.previous = QPushButton(self.frame_4)
        self.previous.setObjectName(u"previous")
        self.previous.setGeometry(QRect(0, 170, 51, 51))
        self.next = QPushButton(self.frame_4)
        self.next.setObjectName(u"next")
        self.next.setGeometry(QRect(430, 170, 51, 51))
        self.learnerScreen.addWidget(self.alphabetScreen)
        self.testScreen = QWidget()
        self.testScreen.setObjectName(u"testScreen")
        self.learnerScreen.addWidget(self.testScreen)
        self.secondScreen.addWidget(self.learnerPage)
        self.speakerPage = QWidget()
        self.speakerPage.setObjectName(u"speakerPage")
        self.imageOutput = QLabel(self.speakerPage)
        self.imageOutput.setObjectName(u"imageOutput")
        self.imageOutput.setGeometry(QRect(10, 10, 621, 371))
        self.startBtn2 = QPushButton(self.speakerPage)
        self.startBtn2.setObjectName(u"startBtn2")
        self.startBtn2.setGeometry(QRect(260, 400, 141, 51))
        self.secondScreen.addWidget(self.speakerPage)
        self.feedbackPage = QWidget()
        self.feedbackPage.setObjectName(u"feedbackPage")
        self.secondScreen.addWidget(self.feedbackPage)
        self.firstScreen.addWidget(self.SecondPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.signerBtn1.setText("")
        self.speakerBtn1.setText("")
        self.learnerBtn1.setText("")
        self.label1.setText(QCoreApplication.translate("MainWindow", u"What role would you like to choose?", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"N(S)L", None))
        self.signerBtn2.setText(QCoreApplication.translate("MainWindow", u"Signer", None))
        self.speakerBtn2.setText(QCoreApplication.translate("MainWindow", u"Speaker", None))
        self.learnerBtn2.setText(QCoreApplication.translate("MainWindow", u"Learner", None))
        self.feedback2.setText(QCoreApplication.translate("MainWindow", u"Feedback", None))
        self.cameraLabel.setText(QCoreApplication.translate("MainWindow", u"cam", None))
        self.startBtn1.setText(QCoreApplication.translate("MainWindow", u"Start/Stop", None))
        self.soundButton2.setText("")
        self.outputLabel.setText(QCoreApplication.translate("MainWindow", u"Output", None))
        self.Alphabets.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.Test.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"NSL Alphabets", None))
        self.alphabet.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.letter.setText(QCoreApplication.translate("MainWindow", u"Ka", None))
        self.previous.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.next.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.imageOutput.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.startBtn2.setText(QCoreApplication.translate("MainWindow", u"Start/Stop", None))
    # retranslateUi

